[workspace]
members = [
  "crates/tweet-model",
  "crates/tweet-route",
  "crates/tweet-fetch",
  "crates/tweet-broadcast",
  "crates/tweet-discord",
]

[profile.release]
debug = 1  # line information only
lto = true
